### ISSUE TITLE
What is Rails doing?

### ISSUE THREAD

**Issue by j6k4m8** [bcwik9/robinhood-on-rails#18]
Does this application rely on Rails-specific server-side functionality or API calls? I wonder if there's a way to strip all server-side functionality from this and run it as a simple HTML page.

**Comment by bcwik9** [comment]
It is possible to do most of this all in HTML/javascript, since the functionality is relying on API calls to Robinhood. I chose Rails since I'm familiar with the stack, and wasn't sure how much I wanted to expand on the functionality provided by Robinhood.
Rails currently handles the following:
* Generating the dynamic HTML to send to the client
* Managing database information such as the user's stock dividers (and potentially future info such as multiple watchlists, since Robinhood only supports one)

If someone were to rewrite this to be HTML/js based, the hardest thing in my opinion would be doing the rewrite of the dynamic HTML, since it's currently in [haml](http://haml.info/)

**Comment by j6k4m8** [comment]
Gotcha! Possibly interesting to leverage [webpack](https://www.npmjs.com/package/haml-loader) or other preloaders to do that heavy lifting for us. 

Just was curious, in the interest of running this on cheaper infrastructure. I'll keep you updated if I move in that direction!

**Comment by bcwik9** [comment]
Ah yea, webpack seems cool.

I've thought about moving everything to HTML before, so it would run on Github pages or something, but ultimately just haven't done it yet

**Comment by pavanagrawal123** [comment]
@j6k4m8 An issue I think you would run into would be that api.robinhood.com doesn't accept cross-origin request, so you would need a server running a proxy to serve the API to the application.

**Comment by j6k4m8** [comment]
Ah @pavanagrawal123 that's interesting. 

We could possibly leverage [YQL](https://developer.yahoo.com/yql/) or write our own AWS lambda endpoints if there were enough interest in this. I may start another project that attempts this; @bcwik9 if I do, are you amenable to me posting a link here?

**Comment by bcwik9** [comment]
Go for it

**Comment by bcwik9** [comment]
Closing this for now, feel free to reopen for new developments

**Comment by bcwik9** [comment]
I should also mention that there are now database components being used, which ties in to Rails more than when I made my previous comments.
