### ISSUE TITLE
Feature: Show average cost of positions under Portfolio

### ISSUE THREAD

**Issue by cdtweb** [bcwik9/robinhood-on-rails#25]
It would be nice to see the avg. versus the current price to quickly evaluate if your position is positive or negative when considering a sell.

**Comment by bcwik9** [comment]
The `Return` column pretty much shows that. It's the difference between the average buy price and the current price, multiplied by the number of shares. If it's positive, that means your average buy price was lower than the current price. If its negative, then it's the opposite.
Are you looking for the difference per share?

**Comment by cdtweb** [comment]
I am looking for something like ```Avg./Share```, next to ```Price/Share``` (to the left). I think having this value, in addition to ```Return``` would be beneficial. In some of my positions, I look to "average down" so having the average cost per share would be very helpful in this case.

Does that make sense?

**Comment by bcwik9** [comment]
I understand, but basically the same data is already shown as return. You'd average down if your return is negative and you buy shares, since you're average price per share is above the current price. It just doesnt show it like that since it's overall return (I found that more useful when developing it). I can look to add a tooltip or column though if you need to see the price per share, and not just overall return (which is (`current price` - `avg. buy price`) * `number of shares owned`)

**Comment by cdtweb** [comment]
I would like to see the price per share, but if it's not something that makes sense then don't worry about it. I can always consult with my iOS app.

**Comment by bcwik9** [comment]
With the latest code push I added a average buy price column
